version: '3'

services:
  ratings:
    container_name: ratings-g39
    build:
      context: ./ratings
      dockerfile: Dockerfile
    image: g39/ratings
    ports:
      - "9081:9080"
    environment:
      - SERVICE_VERSION=v1
    volumes:
      - ratings_data:/var/lib/ratings

  reviews:
    container_name: reviews-g39
    build:
      context: ./reviews/reviews-wlpcfg
      dockerfile: Dockerfile
    image: reviews-v1/g39
    ports:
      - "9082:9080"
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=false
    volumes:
      - reviews_data:/var/lib/reviews

  details:
    container_name: details-g39
    build:
      context: ./details
      dockerfile: Dockerfile
    image: g39/details
    ports:
      - "9083:9080"
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    volumes:
      - details_data:/var/lib/details

  productpage:
    container_name: productpage-g39
    build:
      context: ./productpage
      dockerfile: Dockerfile
    image: g39/productpage
    ports:
      - "9080:9080"
    environment:
      - GRUP_NUM=39
    volumes:
      - productpage_data:/var/lib/productpage

volumes:
  ratings_data:
  reviews_data:
  details_data:
  productpage_data: